### ISSUE TITLE
URL not selectable

### ISSUE THREAD

**Issue by dmd** [jabyrd3/typeto.me2#1]
The URL in the top bar is not selectable, making it difficult for the initiating user to share it.

I realize you can just copy it from the URL bar, but someone else might not.

Either:

- make it selectable
- click-to-copy
- instead of having the URL there, explicitly tell people to copy the URL from the browser

**Comment by dmd** [comment]
A good Call To Action would be to have the text of the connection instructions pulse (flash bold?) until the connection has been made.

**Comment by jabyrd3** [comment]
wrapped url with a tag, user can right click to copy
added pulse animation on opacity for top header bar

**Comment by jabyrd3** [comment]
for good measure i also added click-to-copy with d18c969

if you right click, it behaves like a normal link tag (useful for debugging, you can open in an incognito window to test)

if you left click, it puts the link in your pastebuffer and updates the header with a message that says so
