### ISSUE TITLE
link to github

### ISSUE THREAD

**Issue by dmd** [jabyrd3/typeto.me2#11]
make a link to the source

**Comment by dmd** [comment]
probably in the top bar add something like ` | github src `

**Comment by jabyrd3** [comment]
e96c08b

<img width="215" alt="Screenshot 2024-01-25 at 4 09 02 PM" src="https://github.com/jabyrd3/typeto.me2/assets/847796/6159728f-59a1-4022-84a1-5e2d2957ddcb">
<img width="1183" alt="Screenshot 2024-01-25 at 4 09 30 PM" src="https://github.com/jabyrd3/typeto.me2/assets/847796/419d0f37-dc33-4bd5-b743-32cd494c6227">

**Comment by dmd** [comment]
This seems to have broken the click-to-copy.
