### ISSUE TITLE
smaller screen please

### ISSUE THREAD

**Issue by dmd** [jabyrd3/typeto.me2#3]
By default it is using a size very slightly bigger than the viewport, which means on load you end up with scrollbars AND the bottom line is hidden by the horizontal scrollbar.

I think the "screen" should be:

- 90% width
- centered in the viewport
  - with a thin border around it - maybe 3 px
- 4:3 aspect ratio

**Comment by jabyrd3** [comment]
i've fixed the vertical overflow issue with b5f1, but i'm going to leave the layout as-is; i am debugging this with a vertical split and my windows are narrow and tall.

i can make a hotkey toggle layout modes, tho. i'll probably want to add a global hotkey layer when i add some more functionality that i'm still thinking-through
